"""course_id

Revision ID: 7fd9326cedfa
Revises: 66f9038be270
Create Date: 2025-08-22 11:04:23.154540

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7fd9326cedfa'
down_revision: str | Sequence[str] | None  = '66f9038be270'
branch_labels: str | Sequence[str] | None = None
depends_on:    str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('memberclasslink', 'class_id', new_column_name='course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memberclasslink', 'course_id', new_column_name='class_id')
    op.alter_column('member', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
